behaviors:
  ArcadeDriver:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 10240
      learning_rate: 2.0e-4
      learning_rate_schedule: linear
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    network_settings:
      vis_encode_type: simple
      normalize: false
      hidden_units: 128
      num_layers: 2
    max_steps: 5.0e5
    time_horizon: 64
    summary_freq: 1000
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
